TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += aeroflex.db
DATA += aeroflex.proto

#=======================================
include $(TOP)/configure/RULES
