TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += aeroflex_2023A.db
DB += aeroflex_2030.db
DB += aeroflex_common.db
DATA += aeroflex_2023A.proto
DATA += aeroflex_2030.proto
DATA += aeroflex_common.proto
#=======================================
include $(TOP)/configure/RULES
